# local SMTP settings
spring.mail.host=localhost
spring.mail.port=1025
spring.mail.username=user
spring.mail.password=pass
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.admin.email=admin@example.com

# database settings
spring.datasource.url=jdbc:h2:file:./data/mailform;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.password=un-tha
spring.datasource.username=t-harada
spring.jpa.database=h2
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.h2.console.enabled=true